<a href="https://colab.research.google.com/github/bayuryunarko/belajar-sklearn/blob/main/2_K_Nearest_Neighbours(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Latihan SKLearn dari channel Youtube "Indonesia Belajar"

##Regression dengan KNN (K-Nearest Neighbours)

- KNN adalah model machine learning yang dapat digunakan untuk melakukan prediksi berdasarkan kedekatan karakteristik dengan sejumlah tetangga terdekat
- Prediksi yang dilakukan dapat diterapkan dengan baik pada classsification maupun regression task

##Sample Dataset

In [2]:
import pandas as pd

sensus = {
    'tinggi' : [158, 170, 183, 191, 155, 163, 180, 158, 178],
    'jk' : ['pria', 'pria', 'pria', 'pria', 'wanita', 'wanita', 'wanita', 'wanita', 'wanita'],
    'berat' : [64, 86, 84, 80, 49, 59, 67, 54, 67]
}

sensus_df = pd.DataFrame(sensus)
sensus_df

tinggi      jk  berat
0     158    pria     64
1     170    pria     86
2     183    pria     84
3     191    pria     80
4     155  wanita     49
5     163  wanita     59
6     180  wanita     67
7     158  wanita     54
8     178  wanita     67

##Regression dengan KNN

##Features dan Target

In [3]:
import numpy as np

X_train = np.array(sensus_df[['tinggi', 'jk']])
y_train = np.array(sensus_df['berat'])

print(f'X_train: \n{X_train}\n')
print(f'y_train: {y_train}')

X_train: 
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [178 'wanita']]

y_train: [64 86 84 80 49 59 67 54 67]


##Preprocess Dataset Konversi Label menjadi Numerik Biner

In [4]:
X_train_transpose = np.transpose(X_train)

print(f'X_train: \n{X_train}\n')
print(f'X_train: \n{X_train_transpose}')

X_train: 
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [178 'wanita']]

X_train: 
[[158 170 183 191 155 163 180 158 178]
 ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita'
  'wanita']]


In [6]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
jk_bin = lb.fit_transform(X_train_transpose[1])

print(f'jk: {X_train_transpose[1]}\n')
print(f'jk_binarised: \n{jk_bin}')

jk: ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita' 'wanita']

jk_binarised: 
[[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [7]:
jk_binarised = jk_bin.flatten()
jk_binarised

array([0, 0, 0, 0, 1, 1, 1, 1, 1])

In [8]:
X_train_transpose[1] = jk_binarised
X_train = X_train_transpose.transpose()

print(f'X_train_transpose: \n{X_train_transpose}\n')
print(f'X_train: \n{X_train}')

X_train_transpose: 
[[158 170 183 191 155 163 180 158 178]
 [0 0 0 0 1 1 1 1 1]]

X_train: 
[[158 0]
 [170 0]
 [183 0]
 [191 0]
 [155 1]
 [163 1]
 [180 1]
 [158 1]
 [178 1]]


##Training KNN Regression Model

In [9]:
from sklearn.neighbors import KNeighborsRegressor

K=3
model = KNeighborsRegressor(n_neighbors = K)
model.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                    weights='uniform')

##Prediksi Berat Badan

In [10]:
X_new = np.array([[155, 1]])
X_new

array([[155,   1]])

In [11]:
y_pred = model.predict(X_new)
y_pred

array([55.66666667])

##Evaluasi KNN Regressionn Model

In [12]:
X_test = np.array([[158, 0], [180,0], [160,1], [169,1]])
y_test = np.array([65, 96, 52, 67])

print(f'X_test : \n{X_test}\n')
print(f'y_test : {y_test}')

X_test : 
[[158   0]
 [180   0]
 [160   1]
 [169   1]]

y_test : [65 96 52 67]


In [13]:
y_predict = model.predict(X_test)
y_predict

array([55.66666667, 72.66666667, 59.        , 70.66666667])

###Metode Evaluasi Coefficient of Determination atau R2

In [14]:
from sklearn.metrics import r2_score

r_squared = r2_score(y_test, y_predict)

print(f'R-squared : {r_squared}')

R-squared : 0.32882011605415873


###Metode Evaluasi Mean Absolute Error (MAE) atau Mean Absolute Deviation (MAD)

MAE is the average of the absolute values of the errors of the prediction

In [15]:
from sklearn.metrics import mean_absolute_error

MAE = mean_absolute_error(y_test, y_predict)

print(f'MAE : {MAE}')

MAE : 10.833333333333334


###Metode Evaluasi Mean Squared Error (MSE) atau Mean Squared Deviation (MSD)

MSE is the average of the squares of the errors of the predictions

In [16]:
from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(y_test, y_predict)

print(f'MSE : {MSE}')

MSE : 173.49999999999997


##Permasalahan Scalling pada Features

Selanjutnya akan dipelajari apakah perbedaan satuan pengukuran yang digunakan akan berdampak pada konsistensi hasil yang didapat. Berikut akan dibandingkan hasil jika menggunakan perbedaan satuan pengukuran meter dan milimeter

In [20]:
 from scipy.spatial.distance import euclidean

#  Tinggi dalam milimeter
X_train = np.array([[1700, 0], [1600, 1]])
X_new = np.array([[1640, 0]])

[euclidean(X_new[0], d) for d in X_train]

[60.0, 40.01249804748511]

In [21]:
#  Tinggi dalam meter
X_train = np.array([[1.700, 0], [1.600, 1]])
X_new = np.array([[1.640, 0]])

[euclidean(X_new[0], d) for d in X_train]

[0.06000000000000005, 1.0007996802557442]

Pada perbandingan yang dilakukan di atas telah ditemukan ketidakkonsistenan hasil jika menggunakan satuan pengukuran yang berbeda meskipun menggunakan dataset yang sama

##Menerapkan Standard Scaler (Standard Score atau Z-Score)

Metode ini merupakan salah satu cara yang bisa dilakukan untuk mengatasi permasalahan scaling pada features. Standardize features by removing the mean and scaling to unit variance.

In [22]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

In [24]:
#  Tinggi dalam milimeter
X_train = np.array([[1700, 0], [1600, 1]])
X_train_scaled = ss.fit_transform(X_train)
print(f'X_train_scaled : \n{X_train_scaled}\n')

X_new = np.array([[1640, 0]])
X_new_scaled = ss.fit_transform(X_new)
print(f'X_new_scaled : \n{X_new_scaled}\n')

jarak = [euclidean(X_new_scaled[0], d) for d in X_train_scaled]
print(f'Jarak : {jarak}')

X_train_scaled : 
[[ 1. -1.]
 [-1.  1.]]

X_new_scaled : 
[[0. 0.]]

Jarak : [1.4142135623730951, 1.4142135623730951]


In [25]:
#  Tinggi dalam meter
X_train = np.array([[1.700, 0], [1.600, 1]])
X_train_scaled = ss.fit_transform(X_train)
print(f'X_train_scaled : \n{X_train_scaled}\n')

X_new = np.array([[1.640, 0]])
X_new_scaled = ss.fit_transform(X_new)
print(f'X_new_scaled : \n{X_new_scaled}\n')

jarak = [euclidean(X_new_scaled[0], d) for d in X_train_scaled]
print(f'Jarak : {jarak}')

X_train_scaled : 
[[ 1. -1.]
 [-1.  1.]]

X_new_scaled : 
[[0. 0.]]

Jarak : [1.4142135623730967, 1.4142135623730934]


##Menerapkan Features Scalling pada KNN

###Dataset

In [40]:
sensus = {
    'tinggi' : [158, 170, 183, 191, 155, 163, 180, 158, 178],
    'jk' : ['pria', 'pria', 'pria', 'pria', 'wanita', 'wanita', 'wanita', 'wanita', 'wanita'],
    'berat' : [64, 86, 84, 80, 49, 59, 67, 54, 67]
}

sensus_df = pd.DataFrame(sensus)
sensus_df

tinggi      jk  berat
0     158    pria     64
1     170    pria     86
2     183    pria     84
3     191    pria     80
4     155  wanita     49
5     163  wanita     59
6     180  wanita     67
7     158  wanita     54
8     178  wanita     67

###Preprocess Dataset

In [41]:
X_train = np.array(sensus_df[['tinggi', 'jk']])
y_train = np.array(sensus_df['berat'])

print(f'X_train: \n{X_train}\n')
print(f'y_train: {y_train}')

X_train: 
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [178 'wanita']]

y_train: [64 86 84 80 49 59 67 54 67]


In [42]:
X_train_transpose = np.transpose(X_train)

print(f'X_train: \n{X_train}\n')
print(f'X_train: \n{X_train_transpose}')

lb = LabelBinarizer()
jk_bin = lb.fit_transform(X_train_transpose[1])

print(f'jk: {X_train_transpose[1]}\n')
print(f'jk_binarised: \n{jk_bin}')

jk_binarised = jk_bin.flatten()

X_train_transpose[1] = jk_binarised
X_train = X_train_transpose.transpose()

print(f'X_train_transpose: \n{X_train_transpose}\n')
print(f'X_train: \n{X_train}')

X_train: 
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [178 'wanita']]

X_train: 
[[158 170 183 191 155 163 180 158 178]
 ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita'
  'wanita']]
jk: ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita' 'wanita']

jk_binarised: 
[[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]
X_train_transpose: 
[[158 170 183 191 155 163 180 158 178]
 [0 0 0 0 1 1 1 1 1]]

X_train: 
[[158 0]
 [170 0]
 [183 0]
 [191 0]
 [155 1]
 [163 1]
 [180 1]
 [158 1]
 [178 1]]


In [43]:
print(f'X_train: \n{X_train}\n')
print(f'y_train: {y_train}')

X_train: 
[[158 0]
 [170 0]
 [183 0]
 [191 0]
 [155 1]
 [163 1]
 [180 1]
 [158 1]
 [178 1]]

y_train: [64 86 84 80 49 59 67 54 67]


###Test Dataset

In [44]:
X_test = np.array([[168, 0], [180,0], [160,1], [169,1]])
y_test = np.array([65, 96, 52, 67])

print(f'X_test : \n{X_test}\n')
print(f'y_test : {y_test}')

X_test : 
[[168   0]
 [180   0]
 [160   1]
 [169   1]]

y_test : [65 96 52 67]


###Feature Scalling dengan Standard Scaler

In [45]:
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.fit_transform(X_test)

print(f'X_train_scaled : \n{X_train_scaled}\n')
print(f'X_test_scaled : \n{X_test_scaled}\n')

X_train_scaled : 
[[-1.04119359 -1.11803399]
 [-0.05479966 -1.11803399]
 [ 1.01379376 -1.11803399]
 [ 1.6713897  -1.11803399]
 [-1.28779207  0.89442719]
 [-0.63019612  0.89442719]
 [ 0.76719527  0.89442719]
 [-1.04119359  0.89442719]
 [ 0.60279629  0.89442719]]

X_test_scaled : 
[[-0.17557375 -1.        ]
 [ 1.50993422 -1.        ]
 [-1.29924573  1.        ]
 [-0.03511475  1.        ]]



###Training dan Evaluasi Model

In [46]:
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

MAE = mean_absolute_error(y_test, y_pred)
MSE = mean_squared_error(y_test, y_pred)

print(f'MAE : {MAE}')
print(f'MSE : {MSE}')

MAE : 7.583333333333336
MSE : 85.13888888888893
